networks:
  side:
    driver: overlay

services:
  minlink:
    image: hub-minlink:latest
    ports:
      - "3015:3015"
    volumes:
      - ./.run.env:/minlink/.run.env
      - ./assets:/minlink/assets
      - ./_volume/_logs/minlink_backend:/logs
    networks:
      - side
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any # no always policy on swarm mode
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        reservations:
          cpus: "0.01"
          memory: 128M
        limits:
          cpus: "0.01"
          memory: 128M