networks:
  webapp:
    driver: overlay
  common:
    driver: overlay

services:
  backend:
    image: minlink-backend:latest
    # open ports in overlay network to communicate each other
    ports:
      - "3010:3010"
    volumes:
      - ./.run.env:/minlink/.run.env
      - ./assets:/minlink/assets
      - ./_volume/_logs/minlink_backend:/logs
    networks:
      - webapp
      - common
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any # no always policy on swarm mode
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        reservations:
          cpus: "0.5"
          memory: 512M
        limits:
          cpus: "1"
          memory: 1024M
  servertunnel:
    image: cloudflare/cloudflared:latest
    env_file: ".run.env"
    command: tunnel --no-autoupdate run
    volumes:
      - ./.run.env/:/.run.env
      # - ./_volume/_logs/minlink_tunnel:/logs
    networks:
      - webapp
      - common
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any # no always policy on swarm mode
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        reservations:
          cpus: "0.5"
          memory: 512M
        limits:
          cpus: "1"
          memory: 1024M
