// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "show main page, returning html",
                "tags": [
                    "view"
                ],
                "summary": "show main page, returning html",
                "responses": {}
            }
        },
        "/api/crawl": {
            "get": {
                "description": "Get server health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api"
                ],
                "summary": "visit tradingview and extract daily dollar index",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.CrawlResponse"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "Get server health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api"
                ],
                "summary": "Show the health status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_api.CrawlResponse": {
            "type": "object",
            "properties": {
                "dxy": {
                    "type": "string"
                }
            }
        },
        "internal_api.HealthResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "minlink API",
	Description:      "minlink backend API documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
